@authAPI = http://localhost:8080
@testAPI_remote_validation = http://localhost:8090
@testAPI_remote_keys = http://localhost:8091

# @name auth_response
GET {{authAPI}}/auth/users/login/attila HTTP/1.1
Content-Type: application/json

@accessToken = {{auth_response.response.body.$.accessToken}}


###

GET {{authAPI}}/auth/tokens/validation HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

GET {{authAPI}}/auth/jwk HTTP/1.1
Content-Type: application/json


###

GET {{authAPI}}/users/near HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###

GET {{testAPI_remote_validation}}/users/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

GET {{testAPI_remote_keys}}/users/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}